spring.application.name=lukingStore
# Microsoft SQL Server Connection Properties
spring.datasource.url=jdbc:sqlserver://PC-DANIEL\SQLEXPRESS:1433;databaseName=lukingStore;encrypt=true;trustServerCertificate=true
spring.datasource.username=daniel
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
